### ISSUE TITLE
hanning()

### ISSUE THREAD

**Issue by stacyderuiter** [stacyderuiter/TagTools#1]
the hanning() function does not produce the same results in matlab, octave, and R. We need to track down the source of the discrepancy and find a solution.

**Comment by yejoo24** [comment]
Octave and R produces the same code, since the R code derives from R. From what I understand, the hanning window function comes from the equation w(n)=0.5(1−cos(2πn/N)),0≤n≤N. However, matlab and R/Octave chooses a different number for n and N of that equation. On matlab, n starts from 0 and ends at half of the number given by user input, and N is given as user input + 1. The answer from the equation is then mirrored from front to back to produce a symmetrical array of numbers. For octave/R, n starts from 0 and ends at user input - 1. N is also defined as user input - 1 in Octave/R.  
There are ways, however, to result in similar answers, except for the data in Octave/R starting and ending in 0. For example, hanning(4) in matlab gives 0.3455, 0.9045, 0.9045, 0.3455. While hanning(4) gives 0. 0.75, 0.75, 0, hanning(6) in Octave/R gives 0, 0.3455, 0.9045, 0.9045, 0.3455, 0. There might be a work around, if we can add 2 to the given number and take out the first and last number in speclev (which uses hanning) for octave and R.  The question is which answer is correct: the matlab version or the Octave/R version? I hope tomorrow's talk clarifies which is preferred over the other.

**Comment by yejoo24** [comment]
I think I fixed this in R. I just need to do it the same way in Octave. The speclev function that uses hanning produces the same results as in matlab.

**Comment by stacyderuiter** [comment]
Great! Can you please report back to me in person sometime exactly what was
going on, and what you did?
